---
- name: update apt-cache
  apt: update_cache=yes

- name: Install apache2
  apt: name=apache2 state=latest

- name: Create custom docroot
  file: path=/var/www/example state=directory owner=www-data group=www-data

- name: Set up HTML file
  copy: src=index.html dest=/var/www/example/index.html owner=www-data group=www-data

- name: Set up Apache vhost file
  template: src=vhost.tpl dest=/etc/apache2/sites-available/000-default.conf

- name: Restart apache service
  service: name=apache2 state=restarted
