---
driver:
  name: vagrant

transport:
  name: sftp

provisioner:
  hosts: all
  name: ansible_playbook
  roles_path: roles
  require_chef_for_busser: false
  require_ruby_for_busser: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
  - name: apache_server

verifier:
  ruby_bindir: '/usr/bin'
