---
driver:
  name: vagrant

transport:
  name: sftp

provisioner:
  require_chef_for_busser: false
  require_ruby_for_busser: true
  hosts: all
  name: ansible_playbook

platforms:
  - name: ubuntu-14.04

suites:
  - name: default

verifier:
  ruby_bindir: '/usr/bin'
