---
driver:
  name: docker
  use_sudo: false

transport:
  name: sftp

provisioner:
  hosts: all
  name: ansible_playbook
  roles_path: roles
  #require_chef_for_busser: false
  #require_ruby_for_busser: true

platforms:
  - name: ubuntu-16.04

suites:
  - name: linux_common
  - name: apache_server
  - name: my_linux_desktop
    provisioner:
      playbook: my_linux_desktop.yml
    #    provisioner:
    #      name: ansible_playbook
    #      playbook: main.yml

verifier:
    #  name: "kitchen-verifier-serverspec"
    #ruby_bindir: '/usr/bin'
